import { chromium } from 'playwright';
const out = '/sessions/great-gifted-clarke/mnt/outputs';
const b = await chromium.launch({ args: ['--no-sandbox','--disable-gpu','--disable-dev-shm-usage'] });
let p = await b.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 2 });
await p.goto('http://localhost:3211', { waitUntil: 'networkidle' });
await p.waitForTimeout(2600);
await p.screenshot({ path: out + '/light_hero_desktop.png' });
await p.screenshot({ path: out + '/light_full_desktop.png', fullPage: true });
let m = await b.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2 });
await m.goto('http://localhost:3211', { waitUntil: 'networkidle' });
await m.waitForTimeout(2600);
await m.screenshot({ path: out + '/light_hero_mobile.png' });
await b.close();
console.log('shots done');
